add_newline = false
format = """$directory$character"""
right_format = """$all"""

[directory]
truncation_length = 2

[git_branch]
symbol = "ğŸŒ± "
format =  "[$symbol$branch (:$remote_branch)]($style)"

[cmd_duration]
min_time = 20_000

[sudo]
symbol = "âš¡ "
format = "[$symbol]($style)"
disabled = false

[python]
detect_extensions = []
detect_files = ["__init__.py", "requirements.txt", "pyproject.toml", "setup.py"]

[custom.docker]
command = "echo ğŸ‹"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
